spring:
  application:
    name: oauth2-server

server:
  port: 6010
  servlet:
    context-path: /oauth2-authorization
    
logging:
  file: /logs/oauth2-authorization
  level:
    org:
      springframework:
        web: debug
        security: debug

